#! /usr/bin/env perl
use strict;
use warnings FATAL => 'all';
use JSON;

use Bio::SFF::Reader;
die 'No argument given' if not @ARGV;
my $reader = Bio::SFF::Reader->new(file => $ARGV[0]);
print encode_json({ %{ $reader->read_entry} });
