#! /usr/bin/env perl
use strict;
use warnings FATAL => 'all';

use Bio::SFF::Reader;
die 'No argument given' if not @ARGV;
my $reader = Bio::SFF::Reader->new(file => $ARGV[0]);

1 while $reader->next_entry;
